-- MySQL Script generated by MySQL Workbench
-- Tue Aug  9 20:08:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Editorial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Editorial` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Editorial` (
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Libro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Libro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Libro` (
  `ISBN` INT NOT NULL,
  `Titulo` VARCHAR(45) NOT NULL,
  `Formato` VARCHAR(2) NULL,
  `Editorial_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ISBN`),
  INDEX `fk_Libro_Editorial_idx` (`Editorial_nombre` ASC) VISIBLE,
  CONSTRAINT `fk_Libro_Editorial`
    FOREIGN KEY (`Editorial_nombre`)
    REFERENCES `mydb`.`Editorial` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Autor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Autor` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha_nac` DATETIME NULL,
  `nacionalidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Libro_has_Autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Libro_has_Autor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Libro_has_Autor` (
  `Libro_ISBN` INT NOT NULL,
  `Autor_codigo` INT NOT NULL,
  PRIMARY KEY (`Libro_ISBN`, `Autor_codigo`),
  INDEX `fk_Libro_has_Autor_Autor1_idx` (`Autor_codigo` ASC) VISIBLE,
  INDEX `fk_Libro_has_Autor_Libro1_idx` (`Libro_ISBN` ASC) INVISIBLE,
  CONSTRAINT `fk_Libro_has_Autor_Libro1`
    FOREIGN KEY (`Libro_ISBN`)
    REFERENCES `mydb`.`Libro` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libro_has_Autor_Autor1`
    FOREIGN KEY (`Autor_codigo`)
    REFERENCES `mydb`.`Autor` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
